// Generated by CoffeeScript 1.8.0
(function() {
  var keystone;

  require("dotenv").load();

  keystone = require("keystone");

  keystone.init({
    name: "Stuyvesant Spectator",
    brand: "Stuyvesant Spectator",
    less: "public",
    "static": "public",
    favicon: "public/favicon.ico",
    views: "templates/views",
    "view engine": "jade",
    emails: "templates/emails",
    "auto update": true,
    session: true,
    auth: true,
    "user model": "User",
    "cookie secret": "f!\"XNp{}%\"[`Z5Jm._|[y>QPqnk@{^#w@T3S(S]e)B?7!9`B|6#,nI$H<1y*Q&9-"
  });

  keystone["import"]("models");

  keystone.set("locals", {
    _: require('lodash/dist/lodash.underscore'),
    env: keystone.get("env"),
    utils: keystone.utils,
    editable: keystone.content.editable
  });

  keystone.set("routes", require("./routes"));

  keystone.set("email locals", {
    logo_src: "/images/logo-email.gif",
    logo_width: 194,
    logo_height: 76,
    theme: {
      email_bg: "#f9f9f9",
      link_color: "#2697de",
      buttons: {
        color: "#fff",
        background_color: "#2697de",
        border_color: "#1a7cb7"
      }
    }
  });

  keystone.set("email rules", [
    {
      find: "/images/",
      replace: (keystone.get("env") === "production" ? "http://www.your-server.com/images/" : "http://localhost:3000/images/")
    }, {
      find: "/keystone/",
      replace: (keystone.get("env") === "production" ? "http://www.your-server.com/keystone/" : "http://localhost:3000/keystone/")
    }
  ]);

  keystone.set("email tests", require("./routes/emails"));

  keystone.set("nav", {
    users: "users"
  });

  keystone.start();

}).call(this);

//# sourceMappingURL=keystone.js.map
