// Generated by CoffeeScript 1.8.0
(function() {
  var auth_fail, login_fail, login_success, passport;

  passport = require("passport");

  module.exports = {
    process: function(req, res) {
      console.log('controller called');
      passport.authenticate("local", function(err, user, info) {
        console.log('start auth');
        if (err || (!user)) {
          auth_fail(req, res);
        } else {
          req.logIn(user, function(err) {
            if (err) {
              login_fail(req, res);
            } else {
              login_success(req, res);
            }
          });
        }
      })(req, res);
    },
    logout: function(req, res) {
      req.logout();
      res.ok("Logout successful");
      if (!req.wantsJSON) {
        return res.redirect("/");
      }
    },
    _config: {}
  };

  auth_fail = function(req, res) {
    console.log('auth fail');
    res.badRequest("Authentication failed");
    if (!req.wantsJSON) {
      return res.redirect("/login");
    }
  };

  login_fail = function(req, res) {
    console.log('login fail');
    res.badRequest("Login failed");
    if (!req.wantsJSON) {
      return res.redirect("/login");
    }
  };

  login_success = function(req, res) {
    console.log('login succes');
    res.ok("Login successful");
    if (!req.wantsJSON) {
      return res.redirect("/");
    }
  };

}).call(this);
